name: Java CI with Maven
on:
  push:
    branches-ignore:
    - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.21
      uses: actions/setup-java@v3
  
      with:
        distribution: 'temurin'
        java-version: 21.0.7+6
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn -B --file pom.xml -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }} verify coveralls:report
